title: Github Pages 101
author: Devvrat Shukla
email: devvratshukla@gmail.com
description: > Learn more about the github pages.

# social links
twitter_username: devvratio
github_username:  devvratshukla

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-dinky
